jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 360
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco upgrade %ROS_METAPACKAGE% -y
      robocopy "." ".\src\cartographer_ros" /E /MOVE /XD "src" > NUL
      cmd /C "cd src && git clone https://github.com/larics/cartographer --branch windows"
      call "C:\opt\ros\melodic\x64\env.bat" rosdep install --from-paths . --ignore-src -r -y
      powershell -Command "Invoke-WebRequest -OutFile C:\opt\ros\melodic\x64\bin\catkin_make_isolated https://raw.githubusercontent.com/ros/catkin/e98ee68d675f0ce6ad6297346743623f72f4da05/bin/catkin_make_isolated"
    env:
      ROS_METAPACKAGE: 'ros-melodic-desktop'
    displayName: Install prerequisites

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      set PATH=%PATH:C:\tools\mingw64\bin;=%
      set PATH=%PATH:C:\Program Files\Git\bin;=%
      set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
      set PATH=%PATH:C:\Program Files\Git\mingw64\bin;=%
      catkin_make_isolated --use-ninja --install
    displayName: Build

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      set PATH=%PATH:C:\tools\mingw64\bin;=%
      set PATH=%PATH:C:\Program Files\Git\bin;=%
      set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
      set PATH=%PATH:C:\Program Files\Git\mingw64\bin;=%
      cd build_isolated\cartographer\install && ctest --no-compress-output -T Test
    displayName: Run cartographer tests
    
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      set PATH=%PATH:C:\tools\mingw64\bin;=%
      set PATH=%PATH:C:\Program Files\Git\bin;=%
      set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
      set PATH=%PATH:C:\Program Files\Git\mingw64\bin;=%
      cd build_isolated\cartographer_ros && ninja tests && ctest --no-compress-output -T Test
    displayName: Build and run cartographer_ros tests
   
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      set PATH=%PATH:C:\tools\mingw64\bin;=%
      set PATH=%PATH:C:\Program Files\Git\bin;=%
      set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
      set PATH=%PATH:C:\Program Files\Git\mingw64\bin;=%
      python src\cartographer\scripts\ctest_to_junit.py build_isolated\cartographer_ros
    displayName: Convert tests to jUnit
    condition: always()

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testRunner: 'jUnit'
      testResultsFiles: '**\jUnit.xml'
      searchFolder: '$(Build.SourcesDirectory)\build_isolated\cartographer_ros\Testing'
    condition: always()